version: '3'

vars:
  CMD: mpm

tasks:
  build:
    sources:
      - main.go
      - go.mod
      - go.sum
      - internal/**/*.go
    generates:
      - ./build/{{.CMD}}{{exeExt}}
    cmds:
      - cmd: "go build -v -o ./build/{{.CMD}}{{exeExt}}"
  
  install:
    deps: [build]
    cmds:
      - cmd: go install