version: '3'

tasks:
  build:
    sources:
      - main.go
      - go.mod
      - go.sum
      - internal/**/*.go
    generates:
      - build/mingle
      - build/mingle.exe
    cmds:
      - cmd: go build -o build/mingle.exe
        platforms: [windows]
      - cmd: go build -o build/mingle
        platforms: [darwin, linux]
  
  install:
    deps: [build]
    cmds:
      - cmd: go install